import { GravityStarsBackground } from '@/components/animate-ui/components/backgrounds/gravity-stars';
import { QueryProvider } from '@/components/providers/query-provider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Nigiri',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <GravityStarsBackground className="absolute inset-0 flex items-center justify-center rounded-xl" />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
